//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplierPlatform.APP_WSServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APP_WSServiceReference.APP_WSSoap")]
    public interface APP_WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LOGIN(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIN", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LOGINAsync(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIN_V1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LOGIN_V1(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIN_V1", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LOGIN_V1Async(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIN_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LOGIN_V2(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse, string strLoginInputJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGIN_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LOGIN_V2Async(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse, string strLoginInputJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGOUT_INHOUSE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LOGOUT_INHOUSE(string USER_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGOUT_INHOUSE", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LOGOUT_INHOUSEAsync(string USER_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGOUT_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LOGOUT_V2(string strApp_ID, string strLogin_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGOUT_V2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LOGOUT_V2Async(string strApp_ID, string strLogin_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGOUT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LOGOUT(string strApp_ID, string strLogin_ID, string strApp_type, string strMAC, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LOGOUT", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LOGOUTAsync(string strApp_ID, string strLogin_ID, string strApp_type, string strMAC, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_VERIFY_CODE_S", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CHECK_VERIFY_CODE_S(string strLogin_ID, string strApp_ID, string strVerify_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_VERIFY_CODE_S", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CHECK_VERIFY_CODE_SAsync(string strLogin_ID, string strApp_ID, string strVerify_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_VERIFY_CODE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CHECK_VERIFY_CODE(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string strVerify_code, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_VERIFY_CODE", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CHECK_VERIFY_CODEAsync(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string strVerify_code, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePushKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePushKey(string strLogin_ID, string strApp_ID, string strApp_Type, string strVerifyCode, string strPhsuKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePushKey", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePushKeyAsync(string strLogin_ID, string strApp_ID, string strApp_Type, string strVerifyCode, string strPhsuKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_APPVERSION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CHECK_APPVERSION(string strApp_ID, string strApp_Type, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CHECK_APPVERSION", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CHECK_APPVERSIONAsync(string strApp_ID, string strApp_Type, string IsInhouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_USR_PRFL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GET_USR_PRFL(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string IsInhouse, string strComp_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_USR_PRFL", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GET_USR_PRFLAsync(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string IsInhouse, string strComp_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APP_WSSoapChannel : SupplierPlatform.APP_WSServiceReference.APP_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APP_WSSoapClient : System.ServiceModel.ClientBase<SupplierPlatform.APP_WSServiceReference.APP_WSSoap>, SupplierPlatform.APP_WSServiceReference.APP_WSSoap {
        
        public APP_WSSoapClient() {
        }
        
        public APP_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APP_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APP_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APP_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LOGIN(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse) {
            return base.Channel.LOGIN(strApp_ID, strVerify_Type, strLogin_ID, strPWD, strApp_type, strMAC, strPUSH_KEY, strAPP_VERSION, strOS_VERSION, strMANUFACTURER, strPHONEMODEL, strWIDTHPIXELS, strHEIGHTPIXELS, IsInhouse);
        }
        
        public System.Threading.Tasks.Task<string> LOGINAsync(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse) {
            return base.Channel.LOGINAsync(strApp_ID, strVerify_Type, strLogin_ID, strPWD, strApp_type, strMAC, strPUSH_KEY, strAPP_VERSION, strOS_VERSION, strMANUFACTURER, strPHONEMODEL, strWIDTHPIXELS, strHEIGHTPIXELS, IsInhouse);
        }
        
        public string LOGIN_V1(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse) {
            return base.Channel.LOGIN_V1(strApp_ID, strVerify_Type, strLogin_ID, strPWD, strApp_type, strMAC, strPUSH_KEY, strAPP_VERSION, strOS_VERSION, strMANUFACTURER, strPHONEMODEL, strWIDTHPIXELS, strHEIGHTPIXELS, IsInhouse);
        }
        
        public System.Threading.Tasks.Task<string> LOGIN_V1Async(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse) {
            return base.Channel.LOGIN_V1Async(strApp_ID, strVerify_Type, strLogin_ID, strPWD, strApp_type, strMAC, strPUSH_KEY, strAPP_VERSION, strOS_VERSION, strMANUFACTURER, strPHONEMODEL, strWIDTHPIXELS, strHEIGHTPIXELS, IsInhouse);
        }
        
        public string LOGIN_V2(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse, string strLoginInputJson) {
            return base.Channel.LOGIN_V2(strApp_ID, strVerify_Type, strLogin_ID, strPWD, strApp_type, strMAC, strPUSH_KEY, strAPP_VERSION, strOS_VERSION, strMANUFACTURER, strPHONEMODEL, strWIDTHPIXELS, strHEIGHTPIXELS, IsInhouse, strLoginInputJson);
        }
        
        public System.Threading.Tasks.Task<string> LOGIN_V2Async(string strApp_ID, string strVerify_Type, string strLogin_ID, string strPWD, string strApp_type, string strMAC, string strPUSH_KEY, string strAPP_VERSION, string strOS_VERSION, string strMANUFACTURER, string strPHONEMODEL, string strWIDTHPIXELS, string strHEIGHTPIXELS, string IsInhouse, string strLoginInputJson) {
            return base.Channel.LOGIN_V2Async(strApp_ID, strVerify_Type, strLogin_ID, strPWD, strApp_type, strMAC, strPUSH_KEY, strAPP_VERSION, strOS_VERSION, strMANUFACTURER, strPHONEMODEL, strWIDTHPIXELS, strHEIGHTPIXELS, IsInhouse, strLoginInputJson);
        }
        
        public string LOGOUT_INHOUSE(string USER_ID) {
            return base.Channel.LOGOUT_INHOUSE(USER_ID);
        }
        
        public System.Threading.Tasks.Task<string> LOGOUT_INHOUSEAsync(string USER_ID) {
            return base.Channel.LOGOUT_INHOUSEAsync(USER_ID);
        }
        
        public string LOGOUT_V2(string strApp_ID, string strLogin_ID) {
            return base.Channel.LOGOUT_V2(strApp_ID, strLogin_ID);
        }
        
        public System.Threading.Tasks.Task<string> LOGOUT_V2Async(string strApp_ID, string strLogin_ID) {
            return base.Channel.LOGOUT_V2Async(strApp_ID, strLogin_ID);
        }
        
        public string LOGOUT(string strApp_ID, string strLogin_ID, string strApp_type, string strMAC, string IsInhouse) {
            return base.Channel.LOGOUT(strApp_ID, strLogin_ID, strApp_type, strMAC, IsInhouse);
        }
        
        public System.Threading.Tasks.Task<string> LOGOUTAsync(string strApp_ID, string strLogin_ID, string strApp_type, string strMAC, string IsInhouse) {
            return base.Channel.LOGOUTAsync(strApp_ID, strLogin_ID, strApp_type, strMAC, IsInhouse);
        }
        
        public string CHECK_VERIFY_CODE_S(string strLogin_ID, string strApp_ID, string strVerify_code) {
            return base.Channel.CHECK_VERIFY_CODE_S(strLogin_ID, strApp_ID, strVerify_code);
        }
        
        public System.Threading.Tasks.Task<string> CHECK_VERIFY_CODE_SAsync(string strLogin_ID, string strApp_ID, string strVerify_code) {
            return base.Channel.CHECK_VERIFY_CODE_SAsync(strLogin_ID, strApp_ID, strVerify_code);
        }
        
        public string CHECK_VERIFY_CODE(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string strVerify_code, string IsInhouse) {
            return base.Channel.CHECK_VERIFY_CODE(strLogin_ID, strApp_ID, strMAC, strApp_Type, strVerify_code, IsInhouse);
        }
        
        public System.Threading.Tasks.Task<string> CHECK_VERIFY_CODEAsync(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string strVerify_code, string IsInhouse) {
            return base.Channel.CHECK_VERIFY_CODEAsync(strLogin_ID, strApp_ID, strMAC, strApp_Type, strVerify_code, IsInhouse);
        }
        
        public string UpdatePushKey(string strLogin_ID, string strApp_ID, string strApp_Type, string strVerifyCode, string strPhsuKey) {
            return base.Channel.UpdatePushKey(strLogin_ID, strApp_ID, strApp_Type, strVerifyCode, strPhsuKey);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePushKeyAsync(string strLogin_ID, string strApp_ID, string strApp_Type, string strVerifyCode, string strPhsuKey) {
            return base.Channel.UpdatePushKeyAsync(strLogin_ID, strApp_ID, strApp_Type, strVerifyCode, strPhsuKey);
        }
        
        public string CHECK_APPVERSION(string strApp_ID, string strApp_Type, string IsInhouse) {
            return base.Channel.CHECK_APPVERSION(strApp_ID, strApp_Type, IsInhouse);
        }
        
        public System.Threading.Tasks.Task<string> CHECK_APPVERSIONAsync(string strApp_ID, string strApp_Type, string IsInhouse) {
            return base.Channel.CHECK_APPVERSIONAsync(strApp_ID, strApp_Type, IsInhouse);
        }
        
        public string GET_USR_PRFL(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string IsInhouse, string strComp_ID) {
            return base.Channel.GET_USR_PRFL(strLogin_ID, strApp_ID, strMAC, strApp_Type, IsInhouse, strComp_ID);
        }
        
        public System.Threading.Tasks.Task<string> GET_USR_PRFLAsync(string strLogin_ID, string strApp_ID, string strMAC, string strApp_Type, string IsInhouse, string strComp_ID) {
            return base.Channel.GET_USR_PRFLAsync(strLogin_ID, strApp_ID, strMAC, strApp_Type, IsInhouse, strComp_ID);
        }
    }
}
